version: '3.8'

services:
  app:
    container_name: app
    build: .
    environment:
      - .env
    networks:
      airways-net:
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    volumes:
      - ./src:/usr/app/src
      - ./logs:/usr/app/logs
    restart: always
  postgres:
    container_name: postgres
    build: ./src/database
    env_file:
      - .env
    networks:
      airways-net:
    volumes:
      - ./src/database/data:/var/lib/postgresql/data:rw
      - ./src/database/logs:/var/lib/postgresql/logs:rw
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: always
networks:
  airways-net:
    driver: bridge
